global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: /metrics

  - job_name: 'ingestion'
    static_configs:
      - targets: ['ingestion:8001']

  - job_name: 'sink'
    static_configs:
      - targets: ['sink:8002']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'kafka-ui'
    static_configs:
      - targets: ['kafka-ui:8100']
    metrics_path: /actuator/prometheus

  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']
    metrics_path: /metrics
    scheme: http

  - job_name: 'spark-worker'
    static_configs:
      - targets: ['spark-worker:8081']
    metrics_path: /metrics
    scheme: http
